language: node_js
sudo: false
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
script:
  - npm run test:lint
  - npm run test:coverage
  - npm run report:coverage:coveralls
  - npm run report:coverage:codacy-coverage